#!/usr/bin/env bash
# This script sends file from client to server

File_path="$1"
IP="$2"
USERNAME="$3"
ssh_key="$4"

if [ $# -lt 3 ] 
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -o StrictHostKeyChecking=no -i "$ssh_key" "$File_path" "$USERNAME@$IP":~/
fi
