#!/usr/bin/env bash
# This script creates a new ubuntu machine with all config
sudo apt update
sudo apt install -y nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World" | sudo tee /var/www/html/index.html > /dev/null
sudo service nginx restart
