#!/usr/bin/env bash
# This script creates a new ubuntu machine with all confi


sudo apt-get -y update
sudo apt-get -y install nginx
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
sudo sed -i -f insert.sed /etc/nginx/sites-available/default

sudo service nginx restart
