#!/usr/bin/env bash
# This script creates a new ubuntu machine with all loadbalancer config

sudo apt-get -y update
sudo apt-get install -y haproxy
sudo sed -i -f load.sed /etc/haproxy/haproxy.cfg
sudo haproxy -f /etc/haproxy/haproxy.cfg -c
sudo service haproxy restart
