#!/usr/bin/env bash
# This is a script

touch /var/run/myscript.pid
pid=$(echo $$)
echo $pid > /var/run/myscript.pid

i=0
while ((i < 10))
do
	echo "To infinity and beyond"
	trap "echo I hate the kill command" SIGTERM
	trap "echo Y U no love me?!; exit" SIGINT
	trap "rm -r /var/run/myscript.pid; exit" SIGQUIT SIGTERM
done


