#!/usr/bin/env bash
# This Best School 10 times, but for the 9th iteration, displays Best School

i=0
while ((i <= 10))
do
	if ((i == 9))
	then
		echo "Hi"
		((i++))
		continue
	fi
	echo "Best School"
	((i++))
done
