#!/usr/bin/env bash
# This Best School 10 times, but for the 9th iteration, displays Best School

i=0
while ((i < 10))
do
	if [ "$i" == "3" ]
	then
		echo "bad luck"
	elif [ "$i" == "7" ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
