#!/usr/bin/env bash
# This  script that gives you information about the school file.


file="school"

if [ -e $file ]
then
	echo "school file exist"
	
	if [ ! -s $file ]
	then
		echo "school file is empty"
	else
		echo "school file is not empty"
	fi

	if [ -f $file ]
	then
		echo "school file is a regular file"
	fi
else
	echo "school file does not exist"
fi
